# Generated by Django 2.0.6 on 2018-06-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180607_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tournament_id', models.IntegerField()),
                ('current_score', models.IntegerField()),
                ('current_question', models.IntegerField()),
            ],
        ),
    ]
