# Generated by Django 2.0.2 on 2018-06-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament Name', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(default='Any', max_length=15)),
                ('difficulty', models.CharField(default='Any', max_length=10)),
            ],
        ),
    ]
